### ISSUE TITLE
problem with static page

### ISSUE THREAD

**Issue by edencap** [moodleuulm/moodle-local_staticpage#22]
Hey alex, 
I am attaching a screen shot of the static page as you told me.
(I am using version 3.1.2 theme Eguru).
![mymoodleproblem](https://cloud.githubusercontent.com/assets/25666601/22790479/08448f8a-eeef-11e6-91cd-7467b91f5216.png)

thank you for the help,
Eden.

**Comment by abias** [comment]
Hi Eden,

I can't see the URL of the screenshot, but I assume that this is a staticpage. I can see some HTML fragment at the top of the content area. May I point you to the instructions how to build a static page on https://github.com/moodleuulm/moodle-local_staticpage/blob/master/README.md#creating-static-page-documents? Please create a proper HTML file and try it again.

Thanks,
Alex

**Comment by edencap** [comment]
Hi,
I will explain again:
The screenshot I am sending you is the static page I have problems with.
I have read the instructions at the link you sent me several times before asking your help.
My problem is that the HTML file overrides the site theme.
I am sending you the screenshot again from a diffrent host.
https://s24.postimg.org/4v38skygl/mymoodleproblem.png

Thanks 
Eden.

**Comment by abias** [comment]
Hi Eden,

I will also try to explain again:
* I was able to see the screenshot in your first post, but the screenshot does not contain the URL of the page (in the browser URL line). That's why I said that I can't see the URL of the page.
* I don't completely understand what you mean with "overrides the site theme". Can you please explain in more detail how the staticpage should look like in your point of view + what is displayed wrong on the page?
* Can you please attach the HTML file so that I can have a look at the HTML structure.

Thanks,
Alex

**Comment by edencap** [comment]
Hey Alex,
Sorry, my bad! the URL: http://moodle.ness-college.co.il/local/staticpage/view.php?page=site

The theme layout is blue header and footer and the content is the white part.
The image appear regardless to that layout, so it tops the footer and it's content.
(The Facebook Icon appears on top of it).
The only 'trick' I found is to add blocks to extend the 'white' part to fit the image length,
but as for design it looks bad.
I will add the screenshot of that, The desire outcome would be like the picture but without the blocks on the sides.

I am also attaching the HTML file.

Thanks again,
Eden.

![staticscreenshot](https://cloud.githubusercontent.com/assets/25666601/22821993/3218df40-ef86-11e6-9cfb-e6d8e2c5d2d9.png)

[statichtml.txt](https://github.com/moodleuulm/moodle-local_staticpage/files/766291/statichtml.txt)

**Comment by abias** [comment]
Hi Eden,

Thanks for uploading the HTML file.

Let me give you this feedback:
* Create a simple and proper HTML file. Close all tags - you forgot to close <html> and did not close center and p tags.
* Remove the bgcolor attribute from the body tag to prevent the HTML fragment to be shown at the top of the static page (see https://github.com/moodleuulm/moodle-local_staticpage/issues/16 for detail).
* The reason why the images overlap is because you added CSS absolute positioning to the static page.

In the end, the look of your static page is the result of the HTML you have uploaded, not the result of a bug in the plugin.

The plugin is built to display simple static pages. If you want to add images and CSS to the page, you will have to fiddle until it fits.

I hope this helps.

Thanks,
Alex
