### ISSUE TITLE
Issues together with multilang v2 plugin

### ISSUE THREAD

**Issue by exgenio** [moodleuulm/moodle-local_staticpage#23]
With multilang v2 plugin the pages are not localized as intended. The following example always shows the german version of the title. Content is localized as intended. It seems that the static pages parser can detect the correct language code but only checks for the first occurence of the title and h1 tags. 

<html>
<head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

{mlang de}
        <title>Impressum</title>
{mlang}

{mlang en}
        <title>Imprint</title>
{mlang}

		
</head>
		
</head>
<body>
{mlang de}
        <h1>AGB</h1>
        [Da steht Dein Inhalt]
{mlang}

{mlang en}
        <h1>Terms and Conditions</h1>
        [Your content goes here]
{mlang}

</body>
</html>

**Comment by abias** [comment]
Hi exgenio,

you are talking about https://moodle.org/plugins/filter_multilang2, right?

Then this is strange because we are using the same filter here in Ulm together with static pages.
If you look at https://moodle.uni-ulm.de/static/impressum.html?lang=de an https://moodle.uni-ulm.de/static/impressum.html?lang=en, you will see that everything gets filtered correctly.

Let me ask you some questions:
* Are you using the 3.1 version of the plugin or ideally the latest 3.2 version?
* Do you have set the setting local_staticpage/processfilters to yes?
* Are you really sure that your multilang syntax is correct, i.e. if you paste the HTML in a label activity on a course page, everything gets filtered correctly in all languages?

Thanks,
Alex
