### ISSUE TITLE
I can't upload Files with this Plugin

### ISSUE THREAD

**Issue by jcg678** [moodleuulm/moodle-local_staticpage#24]
I have a problem , I can't upload html files in this plugin ,whe I try upload a file it can connect with the server
I have the last version of this plugin and moodle 3.2
I can upload the file across ftp ? It's works ?
I need help , please
![problem](https://cloud.githubusercontent.com/assets/14834222/23703227/2c1f8d18-03ff-11e7-9686-45b86ccdf857.jpg)

**Comment by abias** [comment]
Hi jcg678,

I am sorry that you are having problems with uploading files, but we need to make sure that this problem is limited to our plugin and not a general plugin in your Moodle installation.

Are you able to upload files somewhere else in Moodle with the Moodle filepicker, for example on /admin/tool/uploaduser/index.php? Are you really uploading a file with .html suffix and nothing else?

Thanks,
Alex

**Comment by jcg678** [comment]
I can upload images and pdf in the blocks without problems.
When I installed the plugin, this installed correctly.
Yes the file have a .html extension.Dont upload with drag and drop neither select the file
![p1](https://cloud.githubusercontent.com/assets/14834222/23704312/88249cca-0404-11e7-90b8-999b3e22cb36.jpg)
![p2](https://cloud.githubusercontent.com/assets/14834222/23704316/8cd49cf2-0404-11e7-8bf8-b59cbcf5e84e.jpg)
When I select the file it only stay loading but dont upload the file

**Comment by abias** [comment]
Hi jcg678,

thanks for adding more details to your issue.

However, I can only say that I cannot reproduce your problem here and that the upload functionality is part of Moodle core, not of our plugin. That's why I am confused that you say uploading files works for you in other areas of Moodle but not in local_staticpage.
