### ISSUE TITLE
Something don't work with french :-(

### ISSUE THREAD

**Issue by jmd87fr** [moodleuulm/moodle-local_staticpage#39]
Hi,
Please, I need dome help to fix some stuff with my Moodle 3.8

- On my stastic page I loose all caracters like: é ê ..

- I have this sentence on the top : YPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">

I use Libre Office to built page and saved as .HTML

Thanks for your help

**Comment by abias** [comment]
Hi @jmd87fr 

please have a look at https://github.com/moodleuulm/moodle-local_staticpage/issues/16 where this problem was already discussed.

The bottom line is:
* Please clean your HTML file from any unnecessary HTML tags and attributes which were inserted by LibreOffice, especially in the body tag.
* local_staticpage is built to process cleanly crafted HTML files and not distorted HTML code which falls out of word processors like LibreOffice.

I hope you get to the point where your HTML file displays correctly.

Cheers,
Alex

**Comment by jmd87fr** [comment]
Thank you @abiais :-)
