### ISSUE TITLE
Moodle 3.10 not work

### ISSUE THREAD

**Issue by JavierGallego** [moodleuulm/moodle-local_staticpage#47]
Hi!, I install the last version of the plugin in my moodle 3.10 but not work properly, in the main menu of the plugin not appear documentation, and list of pages, can help me?

**Comment by abias** [comment]
Hi @JavierGallego ,

as far as I see, Moodle 3.10 did not introduce any breaking changes for this plugin. I have just tested the plugin on 3.10 successfully and will release an official 3.10 release soon.

I assume that there must be another problem in your Moodle setup, especially as I have the understanding that you are installing the plugin for the first time.

Please provide some steps to reproduce or screenshots so that I get a better understanding for your problem and can help you.

Cheers,
Alex
