### ISSUE TITLE
PHP error

### ISSUE THREAD

**Issue by jasimp** [moodleuulm/moodle-local_staticpage#57]
Hi
I am getteing below error
how to solvethis?

PHP Warning:  DOMDocument::loadHTML(): htmlParseEntityRef: expecting ';' in Entity, line: 7 in /home/lms1/public_html/en/local/staticpage/view.php on line 83

**Comment by christianwolters** [comment]
Hi @jasimp,

the error is not directly caused by this plugin, but by the load/parse function that is processing your HTML document.

My best guess: there is an encoding error in line 7 of your HTML document. You could check for any symbols / special characters and convert them into a html entity: https://developer.mozilla.org/en-US/docs/Glossary/Entity.

Best regards
Christian

**Comment by abias** [comment]
Hi @jasimp ,

@christianwolters has basically said it all. Please have a look at your HTML document. Try to run it through https://validator.w3.org/#validate_by_input to make sure that it is valid HTML.

If you have a valid HTML document and the problem persists, please come back to us.

Cheers,
Alex
