### ISSUE TITLE
Meta description tag

### ISSUE THREAD

**Issue by fvendrell** [moodleuulm/moodle-local_staticpage#9]
Thank you very much for this very useful plugin!

I would suggest to add the meta description to the static page (this is important for SEO considerations). This could be obtained from the meta description tag of the original html file.

I would suggest also to add all important informations present in the head tag of the original html file. For example, since we have in this context several URLs pointing to the same page, it would be valuable to include the canonical URL (see https://support.google.com/webmasters/answer/139066?hl=en).

**Comment by abias** [comment]
Hi fvendrell,

thanks for this proposal.

Some time ago, I added support for <style> tags in the head based on a user's request. <meta> tags could be transferred quite similarly. Unfortunately, our resources are quite limited at the moment. Could you (or a developer near you) create a pull request for this feature?


Concerning the canonical URL, I understand the mechanisms of canonical URLs, but I don't understand why there should be several URLs pointing to the same page with the Moodle static pages. Could you please give an example?

Thanks,
Alex

**Comment by fvendrell** [comment]
For example, these 3 URLs point to the same page:
http://www.example.com/static/faq.html
http://www.example.com/local/staticpage/view.php?page=faq
http://www.example.com/local/staticpage/view.php?page=faq&lang=en
Google will interpret these as duplicate content.

Unfortunately, I am not an expert in coding. :-(
It should be quite easy to add code in the file view.php in order to extract from the original html file the meta content between the </title> and </head> tags.
This meta content could then be incorporated to the resulting html file. The function standard_head_html() in lib/outputrenders.php can be slightly modified to do this.
Unfortunately I don't know how to transfert the value of this meta content from the file view.php to outputrenders.php

**Comment by abias** [comment]
Hi fvendrell,

if you don't mind about the position of the meta tags in the _head_ section, you can re-use the few lines of code in view.php which extract the _style_ tag und put it into the _head_ section. The only thing is that you might have more than one _meta_ tag, so you will have to iterate over all items instead of getting only item(0).

Concerning the multiple URLs:
If you use the rewrite rules to enable
http://www.example.com/static/faq.html
URLs, you can disable the
http://www.example.com/local/staticpage/view.php?page=faq
URLs in the staticpage plugin settings at the same time. This way, you will get rid of duplicate URLs and solve the problem automatically. 
And, as there are no automatic indexes of static pages, if you don't link to a static page from somewhere within Moodle, Google won't find the static page. So you can control yourself which page URL is found and which is not.

Alex

**Comment by fvendrell** [comment]
Hi Alex,

Thank you very much for your answer.

I tried another approach: transfer the head content between the < / title > tag and the < / head > tag:

    $html = $staticdoc->saveHTML();
    // Transfer additional html head content (except title)
    $startcut = strpos($html, '</title>') + 8;
    $stopcut = strpos($html, '</head>') - $startcut;
    $CFG->additionalhtmlhead = $CFG->additionalhtmlhead.substr($html, $startcut, $stopcut);
    echo $OUTPUT->header();

The idea is to transfer the head content with minimal changes (as the body content). With the code above, there should be only absolute relative links in the head tag (relative links will not work).

Thank you again for your nice plugin!

Francis

**Comment by abias** [comment]
Thanks, Francis, for this new code snippet. 

If this solution works for you (and other having similar requirements), it's great.

However, I hesitate from putting this into the plugin as it assumes that there are no head tags to transfer before the title head tag. Up to now, the plugin utilizes the PHP DOM functions to extract tags from the source HTML code and I think we should noch leave this approach.

I hope that it's ok for you that I close the ticket now as you seen to have found a solution. If you have more things to discuss, please speak up :)

Thanks,
Alex
